### ISSUE TITLE
feat : 내 동행 목록 조회

### ISSUE THREAD

**Issue by byh9811** [Lets-Travel-Well/are-you-alone-backend#80]
## 🔍Description

- 관심있는 동행 계획을 표시하는 기능 추가
- 관심 동행 / 내가 리더인 동행 / 참가 신청한 동행 / 참가 확정된 동행 / 다녀온 동행 <-- 논의 필요

## 📝Todo

- [ ] todo1
- [ ] todo2
- [ ] todo3
- [ ] todo4

**Comment by doolysmile** [comment]
다른 이슈와 병합
